# Generated by Django 6.0 on 2026-02-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='timezone Asia/Kolkata, Asia/Dubai', max_length=50),
        ),
    ]
