# Generated by Django 6.0 on 2026-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_deleted_useraddress_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
