# Generated by Django 6.0 on 2026-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddress_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
