# Generated by Django 6.0 on 2026-03-13 08:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_wallet_options_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('ORDER', 'Order Payment/Refund'), ('RETURN', 'Return Refund'), ('REFERRAL', 'Referral Reward'), ('MANUAL', 'Admin Adjustment')], max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='txn_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('REFUND', 'Refund')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal'), ('COD', 'Cash on Delivery'), ('WALLET', 'Wallet')], max_length=20),
        ),
    ]
