# Generated by Django 6.0 on 2026-03-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_wallettransaction_transaction_type_and_more'),
        ('shopcore', '0011_remove_coupon_used_by_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('COD', 'Cash on Delivery'), ('WALLET', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shopcore.order'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('ORDER', 'Order Payment'), ('RETURN', 'Return Refund'), ('CANCEL', 'Cancellation Refund'), ('REFERRAL', 'Referral Reward'), ('MANUAL', 'Admin Adjustment')], max_length=20),
        ),
    ]
