# Generated by Django 5.2.1 on 2026-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_wallettransaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
