# Generated by Django 5.2.1 on 2026-04-28 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_wallettransaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
