# Generated by Django 6.0 on 2026-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
