# Generated by Django 6.0 on 2026-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopcore", "0003_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="average_review",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
