# Generated by Django 6.0 on 2026-03-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopcore", "0009_rename_admin_remark_return_admin_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
