# Generated by Django 6.0 on 2026-04-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcore', '0016_return_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
