# Generated by Django 6.0 on 2026-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcore', '0017_orderitem_cancelled_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='return_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
