# Generated by Django 5.2.1 on 2026-04-25 21:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcore', '0019_offer_new_user_coupon_offer_referrer_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_paid_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
