# Generated by Django 6.0 on 2026-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
