# Generated by Django 6.0 on 2026-02-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('newborn', 'Newborn'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
