# Generated by Django 6.0 on 2026-03-05 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Organic_cotton', 'Organic Cotton'), ('Cotton_spandex', 'Cotton Spandex'), ('Cotton_blend', 'Cotton Blend'), ('Cotton_pique', 'Cotton Pique'), ('Cotton_knit', 'Cotton Knit'), ('Cotton_stretch', 'Cotton Stretch'), ('Cotton_polyster', 'Cotton Polyester'), ('Jersey', 'Jersey'), ('Polyester', 'Polyester'), ('Wool', 'Wool'), ('Silk', 'Silk'), ('Denim', 'Denim'), ('Denim_cotton', 'Denim Cotton'), ('Linen', 'Linen'), ('Linen_blend', 'Linen Blend'), ('Fleece', 'Fleece'), ('Velvet', 'Velvet'), ('Wool_blends', 'Wool Blends'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
