# Generated by Django 6.0 on 2026-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_product',
            field=models.TextField(blank=True, help_text='Detailed description of the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Wool', 'Wool'), ('Silk', 'Silk'), ('Denim', 'Denim'), ('Linen', 'Linen'), ('Fleece', 'Fleece'), ('Velvet', 'Velvet'), ('Organic Cotton', 'Organic Cotton'), ('Wool Blends', 'Wool Blends'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
