# Generated by Django 6.0 on 2026-02-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
