# Generated by Django 6.0 on 2026-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_inventory_quantity_added_productvariant_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color",
            field=models.CharField(
                choices=[
                    ("Multi-color", "Multi-color"),
                    ("White", "White"),
                    ("Black", "Black"),
                    ("Gray", "Gray"),
                    ("Light Gray", "Light Gray"),
                    ("Charcoal", "Charcoal"),
                    ("Red", "Red"),
                    ("Maroon", "Maroon"),
                    ("Crimson", "Crimson"),
                    ("Burgundy", "Burgundy"),
                    ("Coral", "Coral"),
                    ("Pink", "Pink"),
                    ("Baby Pink", "Baby Pink"),
                    ("Hot Pink", "Hot Pink"),
                    ("Rose", "Rose"),
                    ("Blush", "Blush"),
                    ("Orange", "Orange"),
                    ("Peach", "Peach"),
                    ("Rust", "Rust"),
                    ("Burnt Orange", "Burnt Orange"),
                    ("Amber", "Amber"),
                    ("Yellow", "Yellow"),
                    ("Mustard", "Mustard"),
                    ("Gold", "Gold"),
                    ("Lemon", "Lemon"),
                    ("Ivory", "Ivory"),
                    ("Green", "Green"),
                    ("Olive", "Olive"),
                    ("Mint", "Mint"),
                    ("Lime", "Lime"),
                    ("Forest Green", "Forest Green"),
                    ("Blue", "Blue"),
                    ("Sky Blue", "Sky Blue"),
                    ("Navy Blue", "Navy Blue"),
                    ("Royal Blue", "Royal Blue"),
                    ("Teal", "Teal"),
                    ("Purple", "Purple"),
                    ("Lavender", "Lavender"),
                    ("Violet", "Violet"),
                    ("Plum", "Plum"),
                    ("Lilac", "Lilac"),
                    ("Brown", "Brown"),
                    ("Beige", "Beige"),
                    ("Tan", "Tan"),
                    ("Khaki", "Khaki"),
                    ("Chocolate", "Chocolate"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("Boys", "Boys"), ("Girls", "Girls"), ("unisex", "Unisex")],
                default="unisex",
                max_length=10,
            ),
        ),
    ]
