# Generated by Django 6.0 on 2026-02-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_about_product_product_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Wool', 'Wool'), ('Silk', 'Silk'), ('Denim', 'Denim'), ('Linen', 'Linen'), ('Fleece', 'Fleece'), ('Velvet', 'Velvet'), ('Organic_cotton', 'Organic Cotton'), ('Wool_blends', 'Wool Blends'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
