# Generated by Django 6.0 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('0-6 months', '0-6 months'), ('6-12 months', '6-12 months'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-5 years', '3-5 years'), ('5-7 years', '5-7 years'), ('7-10 years', '7-10 years'), ('10-12 years', '10-12 years'), ('12-15 years', '12-15 years')], default='0-6 months', max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.ManyToManyField(related_name='products', to='products.agegroup'),
        ),
    ]
