# Generated by Django 6.0 on 2026-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_agegroup_remove_product_age_group_product_age_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroup',
            old_name='label',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='age_group',
            field=models.ManyToManyField(related_name='variants', to='products.agegroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
