# Generated by Django 6.0 on 2026-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_label_agegroup_age_remove_product_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='age_group',
            new_name='ages',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='age',
            field=models.CharField(choices=[('Newborn', 'Newborn'), ('0-3 months', '0-3 months'), ('3-6 months', '3-6 months'), ('6-9 months', '6-9 months'), ('9-12 months', '9-12 months'), ('12-18 months', '12-18 months'), ('18-24 months', '18-24 months'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4-5 years', '4-5 years'), ('5-6 years', '5-6 years'), ('6-7 years', '6-7 years'), ('7-8 years', '7-8 years'), ('8-9 years', '8-9 years'), ('9-10 years', '9-10 years'), ('10-11 years', '10-11 years'), ('11-12 years', '11-12 years'), ('12-13 years', '12-13 years'), ('13-14 years', '13-14 years'), ('14-15 years', '14-15 years')], max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='colors',
            field=models.ManyToManyField(related_name='variants', to='products.color'),
        ),
    ]
