# Generated by Django 6.0 on 2026-02-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_color_rename_age_group_productvariant_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
