# Generated by Django 6.0 on 2026-03-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
