# Generated by Django 6.0 on 2026-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Light Gray', 'Light Gray'), ('Charcoal', 'Charcoal'), ('Red', 'Red'), ('Maroon', 'Maroon'), ('Crimson', 'Crimson'), ('Burgundy', 'Burgundy'), ('Coral', 'Coral'), ('Pink', 'Pink'), ('Baby Pink', 'Baby Pink'), ('Hot Pink', 'Hot Pink'), ('Rose', 'Rose'), ('Blush', 'Blush'), ('Orange', 'Orange'), ('Peach', 'Peach'), ('Rust', 'Rust'), ('Burnt Orange', 'Burnt Orange'), ('Amber', 'Amber'), ('Yellow', 'Yellow'), ('Mustard', 'Mustard'), ('Gold', 'Gold'), ('Lemon', 'Lemon'), ('Ivory', 'Ivory'), ('Green', 'Green'), ('Olive', 'Olive'), ('Mint', 'Mint'), ('Lime', 'Lime'), ('Forest Green', 'Forest Green'), ('Blue', 'Blue'), ('Sky Blue', 'Sky Blue'), ('Navy Blue', 'Navy Blue'), ('Royal Blue', 'Royal Blue'), ('Teal', 'Teal'), ('Purple', 'Purple'), ('Lavender', 'Lavender'), ('Violet', 'Violet'), ('Plum', 'Plum'), ('Lilac', 'Lilac'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Tan', 'Tan'), ('Khaki', 'Khaki'), ('Chocolate', 'Chocolate')], default='White', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
