# Generated by Django 5.2.1 on 2026-04-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_is_featured_and_more'),
        ('shopcore', '0019_offer_new_user_coupon_offer_referrer_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to_products', to='shopcore.offer'),
        ),
    ]
