# Generated by Django 6.0 on 2026-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkiddora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
